CREATE DATABASE [SOTAICHINH]
GO

USE [SOTAICHINH]
GO

CREATE TABLE SOTAICHINH(
ID Int IDENTITY(1,1) PRIMARY KEY,
BALANCE Decimal(10,0),
TYPE_TRANSACTION Nvarchar(20),
DATE_TRANSACTION Smalldatetime,
AMOUNTS_TRANSACTION Decimal(10,0))
GO

INSERT SOTAICHINH VALUES (1000000, N'RECHARGE', GETDATE(), 1000000)