CREATE DATABASE QUANLYSACH
USE QUANLYSACH
GO

drop table SACH

CREATE TABLE SACH(
MASACH int PRIMARY KEY,
TENSACH nvarchar(50),
NHAXUATBAN nvarchar(50),
SOLUONGTONG bigint,
SOLUONGMUON bigint)
GO

INSERT INTO SACH (MASACH, TENSACH, NHAXUATBAN, SOLUONGTONG,SOLUONGMUON)
VALUES (6149, N'KHI NGUOI LON CO DON', N'NXB THANH NIEN', 1000, 200),
	   (2560, N'LAM SAO QUA MON', N'NXB GIAO DUC', 1500, 30),
	   (1560, N'ON THI SAO CHO TOT', N'NXB TUOI AN HOC', 600, 1),
	   (5991, N'EM LAM XONG ROI', N'NXB KIM THANH CONG', 456, 3)

SELECT * FROM SACH
