CREATE DATABASE [QLKHACHSAN]
GO

USE QLKHACHSAN
GO

CREATE TABLE KHACHHANG(
ID int PRIMARY KEY,
TENKHACHHANG Nvarchar(50),
LOAIPHONG Nvarchar(5))
GO

INSERT INTO KHACHHANG(ID, TENKHACHHANG, LOAIPHONG) VALUES
(10, N'NGUYEN THANH PHONG', N'S'),
(11, N'CAO THE MANH', N'A'),
(12, N'LE QUANG TRUONG', N'B')