CREATE DATABASE [QLSACH]
GO

USE QLSACH
GO

CREATE TABLE SACH(
STT int PRIMARY KEY,
TENSACH Nvarchar(50),
TENNGUOIMUON Nvarchar(50))
GO

INSERT INTO SACH(STT, TENSACH, TENNGUOIMUON) VALUES
(10, N'NHAT KY YEU NUOC', N'NGUYEN THANH TAM'),
(11, N'THAN DONG DAT VIET', N'CHUA MUON'),
(12, N'NGAY VUI', N'CHUA MUON'),
(13, N'NHAT KY YEU NUOC', N'CHUA MUON'),
(14, N'SON TINH THUY TINH', N'LE THI THANH THUY'),
(15, N'TUOI THOI CUA TOI', N'CHUA MUON')

IF((SELECT TENNGUOIMUON FROM SACH WHERE TENSACH = N'NGAY VUI') LIKE N'CHUA MUON')
BEGIN UPDATE SACH SET TENNGUOIMUON = N'AAA' WHERE TENSACH = N'NGAY VUI' END

SELECT * FROM SACH

DROP TABLE SACH